language: python
sudo: true
python:
  - "2.7"
  # - "3.4"

services:
  - mongodb

# command to install dependencies
# some are only used for travis/coveralls so we are installing them here only
install:
  - bash setup_test.sh
# command to run tests
# notice: the nose-cov is used because it is compatible with --processes, but produce a .coverage by process
# so we must combine them in the end
script:
  # so to help eventual debug: knowing what exact versions are in use can be rather useful.
  - pip freeze
  # Code static analysis
  - pep8 --max-line-length=100 --exclude='*.pyc, *.cfg, *.log' --ignore='E402' alignak_webui/*
  - pylint --rcfile=.pylintrc alignak_webui/
  - pep257 --select=D300 alignak_webui
  # Code dynamic analysis
  - cd test
  # Delete previously existing coverage results
  - coverage erase
  # Run test suite with py.test running its coverage plugin
  - pytest -v --cov=alignak_webui --cov-config .coveragerc test_*.py
  # Report about coverage
  - coverage report -m
  - cd ..
# specific call to launch coverage data into coveralls.io
after_success:
  # to get coverage data with relative paths and not absolute we have to
  # execute coveralls from the base directory of the project,
  # so we need to move the .coverage file here :
  mv test/.coverage . && coveralls --rcfile=test/.coveragerc
